### PR TITLE
Some patches to allow Debian packaging (and rename the pkginfo file)

### PR DESCRIPTION
**Pull request by alt-graph**
This is a collection of a few patches to
a) enable Debian packaging (this also needs Git tags, which I created on commits in the main branch)
b) have decent Debian package descriptions
c) generate a pkgconfig file `gul17.pc` instead of `libgul17.pc`.

### CODE REVIEW

**Comment by Finii** [comment]
I would also change this to debhelper 12.
Shall I add a commit, you wanna do it?

`compate` file is dropped and `Build-Depend` takes its place with a modified entry.
Plus some rules can be dropped I guess, maybe, because Meson is fully sopported then.

**Comment by alt-graph** [comment]
> I would also change this to debhelper 12. Shall I add a commit, you wanna do it?
> 
> `compat` file is dropped and `Build-Depend` takes its place with a modified entry. Plus some rules can be dropped I guess, maybe, because Meson is fully sopported then.
> 
> _Edit: And advance the `Standards-Version`_

Go ahead, the PR is yours. :)

**Comment by Finii** [comment]
That for the tags lightwight tags are used is still a very bad habit.
According to 'git' they should only be used locally and not pushed.

Whatever, in addition to resulting in the problem the last commit fixes (see its commit message), it ALSO creates less than optimal changelog files - because the person who tagged the version (i.e. has the resposibility for that version) can not be determined. That is clearly stated in the changelog file

```
doocs-gul17-24-12-0 (24.12.0) stable; urgency=low
  * meson: Search for doxygen only if needed  (tag: DOOCSVERSION_24_12_1, tag: DOOCSVERSION_24_12_0)
  * Fix: Release Version 2.12.0
  * Add info on DOOCS releases 24.10.x
  [Note] No tagger-id available, using topmost commit's author-id as maintainer-id
 -- Fini <ulf.fini.jastrow@desy.de>  Mon, 2 Dec 2024 10:50:32 +0100
```

#### Ready to merge from my side, pls have a look

**Comment by alt-graph** [comment]
Looks good to me. :+1:

For my personal taste all the git magic in the build script is way too complex. But that ship has sailed already several years ago... :shrug:

**Comment by Finii** [comment]
> For my personal taste all the git magic in the build script is way too complex. But that ship has sailed already several years ago... 🤷

On the other hand, we could change this behavior with gul17, why not?

Maybe we should start an issue and brainstorm what we expect. I find it also rather complex - maybe it should be in a tool script instead, even if we stick to it.

**Comment by Finii** [comment]
Maybe we could also drop these "two ways to version gul".

**Pull request merged**
